dist: focal
language: node_js
node_js:
  - 18.12.0
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - sandbox
    - development
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    # AWS dev
    - secure: Szi+7Ykk+HbjPcDYXffGS+JFdkf853df+R8L2rqSdp0HGYor9PsjXA2D0tEzMkZOvDfUYOORtwB3rn7XHIeNtoClcw13vCL5fgLo7oS44vuX4bAqwOQTxreKtmvyMHKTq/xx7XHWpQ2FrUoI2O8J+VFvDsMdcR8pCQcCXFoG+Z5+A/+bBytWxLIUbyePgQbxHJvyGxzudgt0wX00aXSRvD778eqDsTfRb+SIdl2/RKz1Km5cwakE+yy5iGCDFlyR1zRch4sZWWqt3y5+H58hRFaVvnrVq8s+FgdFH0SgsOpJRow35B2+H4weUUOHDBifFhI4EmgKIyY37ELikJamF8+pLO4askJoyrG4qlNvLURhNnto8h/NCokJP8cee8SBDXhLlbv0oTe4cv/Y4sqMDnCcBlgYnWSdH5XZ6O76dRUdG4Tnl7ed/W3429ENhI/C6ut42ZssoBjLj9eghCnMKqrXQZUSsbOfAK9jDrmFdWo4zngwPrOMintswgiCzPdSvpTTwYkVXVtIIpntGZ1aujy2hZJcnEEp1BTMDysWnyUJSQtih5qeMV6nPHUw0VNLLbhqGA6WuT/eqTMx0k0aY9riN+r0lg0XD2E096YfGpb9cqsF4f4dDJF+RiwhzAexkgnQTyT0eJG6aQmbunS+VkU643arkGsJnrqg3AY5tU8=
    # AWS prod
    - secure: mRfEbISvBDvA1XVaNXhist5PW7cRDARCcam3cgDGKuXdZHjLdL5EYMovlGwl/+4KOasWW4FqsHll1qSVX7+yy0ztcRseSeruDCFdKugVIrPasQ63ucPfWA2B9iG0W7t7LkvsMM0CG4/AgsfWcVHo3W+k71H3s51I5GakewN5vu9ImxyxNkTUgQjTrh7n4FkVlrhXM93RN/XJhfykFGmRi+BDndWliEujJeIoeT1IH/PrWUJCvcN18E5pos8PiNFLm+22VElco/XEEqwegrH3/FUVqt8mn3FX0roUGClUtOOCvsvhaa7ySr2737WYvTjs65Ohz/SBzDx7JHkM1UNqiqc13NcdMUsRvymqWx0GnbVTBkQBIO+HUSRrRDX/zP2FnXjlyLNn7ccIYgMbss8XEDnqwzeQeOXxdbg3uXjzCRzfkaAeo1VfKJPKP5JfJUjes2UU9wnpsm4kD4HCSq7oPiowwVmecnj3DqIKUNjh+bKQQOHS5Ybj+IIz1V/3vfp1+3mcz77TpcnOuM+ezYUyz6oQEolF5XCoP3+xDzhTlx68ev/jVMfYwwrg+Xuz4nZhAOg4mnh+QH+RzftfDm5oBTZdek2aj3kBS9NVPRBR2Q/Z4MxG8+wYOwQXNsqLcpJGLJ+KxUjGT16QaNeYi3XhuRd6RPxJ+iTQZZZ1orCcihw=
    # Google maps
    - secure: FQ/ZUBpHMiIBOv29jT1QllyL5Glegl3cQfZVUR8IQSWMIg/z7OYItlCQNIs9cL291ofzGV6E2vEhEIwv/rLHlto17kOUo0oUKmW4KTVma4O74mFdIb1c8Y6ZULldoaFbjlHuua4YVXkbPfq02giTZnTg8ECcCeCcfN+HY3I6eNb86x5QRgUnT1EG3eVFcjqG1PTf+OXxqhlwCKTlfil5z4/Yc44L2K3KbjahflBvMLTIT8vacb3+IUbiXEzL7rEehdCyRxk9ZMxiX5m5GiotY8HOPP2w31E/vguoDa7SAUmz1b5Eu/tt9luyB5vn/CYFu1KKjLFtfFGvhXCIQZiwq5hwMlNUf1fkvZKu2hx6n8jPphqm0qwSDjvDZm8FOsJj1Vsl1d/Sj6Vupb875Nkz6zuHM78ZvZrheEzW1M0vj2Gmr/0YKnZ7JnE2Rpl5IzzK0yQZWbt54FqzyiYMNLHq4/mbZ7E6N8VR1BgK5Y2fnQqwynjy+qvjgeNsdYxamktP7OTPKDlb47MlnQ2RyCMVulkP9zWXkf20M2BzwSzbUifJf6HTpbJU9A2qFb/2701Jq6ogO01EDq0W44dk/ULXoggeDbMtaHQCYXORQTgNZnbbeG022X1eoKSsz3HLQTJDGNQZz4HNCoo+V8isxiXetElLYk3ruR63wuogd3b6Gmk=
install: npm install
before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"
after_success:
  - echo 'All tests passed; Preparing to deploy'
  - "./provisioning/deploy"
