language: node_js
node_js:
  - 14
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    # AWS Dev
    - secure: jtRuQu6sfy9Xx7mUizG+dhtxMDPYW+x/wKM5J7HNXovUuPSLSCaoijo1CPazkG9Yj402+E/jq3NdB1YjR4vozAvdUo4rs0ub1ale3AqUxC7UeLUjoZOsmO99jcTVGdgg/xmi5ukMZvnG7gKbnAdi1CLcz5uNKYA48ipz2qxKui5n7zYP+1/GJai+A6Yx2WiUFL4Nx3jeJoV6mRZZQq+LVbJWFvgSmVnIIfnvk/0veeLo9lmhFpTkzr/maRNY0g8h7BKuNmNUqEnJ9KjMuMe6nMY3TFgpZbpPghRqy8a+Nvk0Wc3FqBpM+JdZIRSyL/FHaCyncRjRKpKqz5m5UfdHayTZwmtd2z5OQ+oxpMtO0pMjKKGTpNsi5KYQ4dnQRVAXjBl8uf/Lq7XFeLyXaXS4fzDFiKD4ylW2ONp7hXLiRhXoO/5+f4yS3LaSkiNBsdggRnkNBgTZCgo5NuYOY4mSa6ZeDVten6ki2M0e6Da8TOAZdDohQ+WCSCgqY1uSMSxhtUWFzUx0Dn6b9MZcYvgilC9WOju5Q5q6vH3q85eSGozqe89G7uH4BJKH48WKNC5MO/QzesVsidahr5MqLnzWGhOySaVBgtDl/jhqVrjOrGBNOeA3LKqoKCzzkPtpau5esdgVIqtDaua0hwbqp0sCQduAsCkAkSnUG24D77YLLC8=
install: npm install
before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"
after_success:
  - echo 'All tests passed; Preparing to deploy'
  - "./provisioning/deploy"
