language: node_js
node_js:
  - 14
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    # AWS dev id
    - secure: tzdqSeVn8ckH1P+5kNfpm6arPM8ajcujxyk6YNHMZaSDvlCuKGv1mlFNL2MZXN0bE7jm1ICtDvN1VJBV2bK8Knod5V5g/MxF4fMUQNlwO0d7BP399yR3i1bxb3ELtl54llwnluhhOiVfhQ1lcexpoJJKG8P56ad0gTlwruy+vFwCOxQVlWxxh0WZHLd4Z8ubwIo7xLg0QXHr1Ed32GjGpFl4WSHnQ4/SD//mHYceGz97M9yk5NgcM2sCX8yilrw+xqQZr1dVPCeTNMmSTcZMv1WQlHDkWR/UOKLmYkIbQPlupqA9SiYBJDdofHYBVGfgDkHsMc4f2w7BeCckutKLwjMlUhFCDu6ktJe6mc3C78/aOHLr6NKiRdLztq+Rc/jcR9I7ZdYBwFtpufjXPizYyr9tdo5Kmo7Sl9aVzbAh8xnJ3JtTU3/DBb48o9KmzRTyP85u4zQPIms8+wAf7QuedD4emVHmFGAnVUDbYvTKMvmGgKb5cK3Zc2idTkbboHDTXAKTm9BcLcC0/msB6T72V1WAWdpN2T/3Z1kGfawLU28tCAjbXc20iapAfqlBxWqY5nOWipvF/BGdGBR2vev1C2w34I5YAPawUpg4OtovGAhiK10zPT9RZL+Th7TkgtYiueT0DMwInrmpVInmy9G2/oRI2o7ZVHP+ECSDDd0Q7Nk=
install: npm install
before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"
after_success:
  - echo 'All tests passed; Preparing to deploy'
  - "./provisioning/deploy"
