language: node_js
node_js:
  - 14
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    # AWS dev
    - secure: LK2QFqhQNHc5hiap5IyX0lPALWKQhizBIKn5lBorNK2jjDJr+EteivBaOOBZgd5FNRk6zPIAVi9ZelzOmDoInxvmJunNBiKVHzPB4c0asEd3NGJRvKlHq3IolztOZq+HobFJFFPFuD1mZowIvskOMekQquN9JxY2ATajMELRoP1ig43mrgiVEmoLcgLZLBVWx/kJjU3qu21u3XjHVQyF1nYzCCRrqTGHbP4movobxRLJ6EI5wXCiXwIZ1EaF5lOIjriyLqSmIhRMkJRgolSrRe80yHIcBf+zKGAOrBXO3i6iOOcIOio1bghN6PWUxHMHr7RxYv8Kx+kJnMWYfmYf8ow6/d7GCTLPUnAWhPuAE26xYRcaL1MrhCohvWI5X3wlP+BZoq11AfmLg9TZMv5HEcISpfRIsxytMLnUn4R2BVzqippw1mx1V2ownIc6n17oNkH6V31IHIIZI5uqUUtzsMIjKbJlH+DrZATxlL/QL2wLGp3xYrie5uAjwfnUlBhzYeu6GgRCO0ij4y37w5qJ/enBRDEakHSAZ8d1/Rd0SWyoknASMmZN0qMI1LassXAailUrp+ZhIgTWO2lCfxL7SErmtfN+BxEhFgoARn0u6xtzYTj/k3JF2mUncaEnk1EaZnAIUM37gXwQi3MOXitACnVrb5QSACX1ZsYNrPVpnug=
    # AWS prod
    - secure: Tesb3UrPBPp0bi/+IwYO6mDjo5kM4MInEueapL0OvW8oXg9FEEogsCtFVL+HlI1omLwB/9t07/64PfiKDDvHqIjCQG/e4nbDQjcsCfmeLNq8c9Mho3togDe4EV8xyx6CeuCUMCINkYHWmnqJl+l6Y/LNJ5Q/ITGkfisjL0VZrK+V933ohAF8h1A3mYGcfHQ5Il28Wu4u7L2FocZXXxUOUTW4cfJxCdyJ2FOlocyOcEXygOd0zWPXhaw8SgbHsLy84gp6tBSAHOzPUDvfjSKyfTeS23h+AEa8mwz3rJtwLf1fJzjDTeplw5LN60lNseuVMXvVZsftCKrcDhyFE3kgsTjYkOY96XOfDGdYNA9eZefTAB+sehSG0+3LM/lQEnW5fUb3YDolqRZolu1uMgo1WamHhvZQ/OvV8QDvHWS1ZnqXoAUiUr54bZ8D8hZnpavVVqtZ0jBt2TlkuQFY8VOErxc85IoGCFAw7t4Qp0QfhATyxiwxPyv9ghAVw9pSozv5StsfBRm0vSUB6y/T0KqUxuIW/zOM1AdPJ04IIm182nm4Tk/kvmIPCMGNKYWwjo8UZ1x1OQx9d5ctX4sCh7+MvIn4Y1JxH9KQxKE9Eg12fPZhC0GuiRJsoLLSkKYjw7XxwKE+9N2KKgyj7cm2CDdS4TXTzKxU3+7q9dPU+Ze5vzI=
    # Google maps
    - secure: FQ/ZUBpHMiIBOv29jT1QllyL5Glegl3cQfZVUR8IQSWMIg/z7OYItlCQNIs9cL291ofzGV6E2vEhEIwv/rLHlto17kOUo0oUKmW4KTVma4O74mFdIb1c8Y6ZULldoaFbjlHuua4YVXkbPfq02giTZnTg8ECcCeCcfN+HY3I6eNb86x5QRgUnT1EG3eVFcjqG1PTf+OXxqhlwCKTlfil5z4/Yc44L2K3KbjahflBvMLTIT8vacb3+IUbiXEzL7rEehdCyRxk9ZMxiX5m5GiotY8HOPP2w31E/vguoDa7SAUmz1b5Eu/tt9luyB5vn/CYFu1KKjLFtfFGvhXCIQZiwq5hwMlNUf1fkvZKu2hx6n8jPphqm0qwSDjvDZm8FOsJj1Vsl1d/Sj6Vupb875Nkz6zuHM78ZvZrheEzW1M0vj2Gmr/0YKnZ7JnE2Rpl5IzzK0yQZWbt54FqzyiYMNLHq4/mbZ7E6N8VR1BgK5Y2fnQqwynjy+qvjgeNsdYxamktP7OTPKDlb47MlnQ2RyCMVulkP9zWXkf20M2BzwSzbUifJf6HTpbJU9A2qFb/2701Jq6ogO01EDq0W44dk/ULXoggeDbMtaHQCYXORQTgNZnbbeG022X1eoKSsz3HLQTJDGNQZz4HNCoo+V8isxiXetElLYk3ruR63wuogd3b6Gmk=
install: npm install
before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"
after_success:
  - echo 'All tests passed; Preparing to deploy'
  - "./provisioning/deploy"
