language: node_js

node_js:
- 14

services:
- docker

cache:
  directories:
  - node_modules

branches:
  only:
  - qa
  - production

env:
  global:
  - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  - secure: mJmE1hgjZDf9vIu/btBd/jR3N1Vf9EeQPX12WMV09x8unjDy5QEhdRcAeTPhC+w9d+3e+flxPNmG2FZRQQ5BQWBZL4LEn7d55Fuzv3MjuS98N44Z/8Blma3sWD/fzsliPg3Jp2Fkye9DqCrOhdlkS++ckC2q4kF4hiEs1w+54Jf0YO2HrsEk8xCneM291uXKCr1hmjl8E4T9LLuKHDsbVL7gzOelvwu2pPl1DRD+hehzzW0VH16Z8xPSeRZjL0Pg+zeR2m7n6lg0u7NYcZFkfqVuwWG7lDllONNAlhlWXQb9WPYUEAysuhUfra5+EQlN6vPB7SWgjFk2km5A1Ht5fqBw1j9C9/SEUMJH/g1xeKDPD2gK3Adw12VI53HYvzmQftDBK3xJ0b5onkUJ2sp0wwDfi3bxwWHDEd76fwOUcZIdeV9YQt0Azkf+cE8K6XgZx0jgwXIDgyKSSdlNC5a1Z0lc5BpdcYHpPPHW9hbJ0HNpIvUBeN/1jgCVofej4dDd887x+rdFecaKtbiCB6G9tnstZfQaabxtFGW80wqqsEEvwA2rJnqBcDb5iqhNdszwroTrnuo0U9ze6Z0IvaReo1JFalG/Qx1xTQcuXfj/1l51IyzC7VrM2ibnG8YbR8Wh3tUtIcJNeDu9SObBtzXHP0wpeLyrdB5u8op/0irCno0=

install: npm install

before_script:
  - cp .travis/.env .
  - ./provisioning/set-env

after_success:
  - echo 'All tests passed; Preparing to deploy'
  - ./provisioning/deploy