language: node_js
node_js:
  - 14
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    # AWS dev
    - secure: DScoq/CwDtJsqZb0KfPvX7FeiZLTgZDbD/YfxKccAisLt9/beiitpqislGZn08DCV0RkQZgMkV/qbGm1kshreYGqh0ZfXZ0ZPMEjSK6JCPKb7Aw0RJsB/GvTxD9wv3iYeK03/JQ6Ty4BPmCMDISL507gkNYz+6aZ/h6tt0lk511sNCowmBxwfVigcYmzBK2FReHGPTU/2AA0iXYl97F6fJs0Q1eBVWxnOF9LwMR2quogoX0k4G911BxQh1nE3ceFLs5tthwzcc66ifotxsLPCtbQ0nyO/mR//MgTAWyCeH6Nz5MR+svxwCzwXaJabsmd50TBvw6pbOsdGFiVO6n6ZGbeUvpayoP/899lOFzkyBm2vUqV+fshEFHWsZmxIoWmU3/bXczB/YVJQZqx0bXulykg0yTH+LYfTpmVebNvIUrZ354cSTKZa51Z04xSo/fwyERX0umPIYnSUA2autc0XDRjJ/6gEKCSdmmMCKjQGaN7tpaS6At85x6xBb8z6kth8xt7PGR/mT3fbp6KMwvTLv+Pu/W3aXAVL3h7lWQ2eQDepSjyHfgcQEt2xXzc1Y94w/codZo0lZxAqZQOrEM+O5opsdxfi1XXhMZMj33rmH2FNIDyUXXZDHTL4hh210rOZVbYHvJdOHaq5kz7TD0RV0dXXKOiXnucN2qOkHIVuBw=
install: npm install
before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"
after_success:
  - echo 'All tests passed; Preparing to deploy'
  - "./provisioning/deploy"
