language: node_js
node_js:
  - 14
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    # AWS dev
    - secure: jtRuQu6sfy9Xx7mUizG+dhtxMDPYW+x/wKM5J7HNXovUuPSLSCaoijo1CPazkG9Yj402+E/jq3NdB1YjR4vozAvdUo4rs0ub1ale3AqUxC7UeLUjoZOsmO99jcTVGdgg/xmi5ukMZvnG7gKbnAdi1CLcz5uNKYA48ipz2qxKui5n7zYP+1/GJai+A6Yx2WiUFL4Nx3jeJoV6mRZZQq+LVbJWFvgSmVnIIfnvk/0veeLo9lmhFpTkzr/maRNY0g8h7BKuNmNUqEnJ9KjMuMe6nMY3TFgpZbpPghRqy8a+Nvk0Wc3FqBpM+JdZIRSyL/FHaCyncRjRKpKqz5m5UfdHayTZwmtd2z5OQ+oxpMtO0pMjKKGTpNsi5KYQ4dnQRVAXjBl8uf/Lq7XFeLyXaXS4fzDFiKD4ylW2ONp7hXLiRhXoO/5+f4yS3LaSkiNBsdggRnkNBgTZCgo5NuYOY4mSa6ZeDVten6ki2M0e6Da8TOAZdDohQ+WCSCgqY1uSMSxhtUWFzUx0Dn6b9MZcYvgilC9WOju5Q5q6vH3q85eSGozqe89G7uH4BJKH48WKNC5MO/QzesVsidahr5MqLnzWGhOySaVBgtDl/jhqVrjOrGBNOeA3LKqoKCzzkPtpau5esdgVIqtDaua0hwbqp0sCQduAsCkAkSnUG24D77YLLC8=
    - secure: LK2QFqhQNHc5hiap5IyX0lPALWKQhizBIKn5lBorNK2jjDJr+EteivBaOOBZgd5FNRk6zPIAVi9ZelzOmDoInxvmJunNBiKVHzPB4c0asEd3NGJRvKlHq3IolztOZq+HobFJFFPFuD1mZowIvskOMekQquN9JxY2ATajMELRoP1ig43mrgiVEmoLcgLZLBVWx/kJjU3qu21u3XjHVQyF1nYzCCRrqTGHbP4movobxRLJ6EI5wXCiXwIZ1EaF5lOIjriyLqSmIhRMkJRgolSrRe80yHIcBf+zKGAOrBXO3i6iOOcIOio1bghN6PWUxHMHr7RxYv8Kx+kJnMWYfmYf8ow6/d7GCTLPUnAWhPuAE26xYRcaL1MrhCohvWI5X3wlP+BZoq11AfmLg9TZMv5HEcISpfRIsxytMLnUn4R2BVzqippw1mx1V2ownIc6n17oNkH6V31IHIIZI5uqUUtzsMIjKbJlH+DrZATxlL/QL2wLGp3xYrie5uAjwfnUlBhzYeu6GgRCO0ij4y37w5qJ/enBRDEakHSAZ8d1/Rd0SWyoknASMmZN0qMI1LassXAailUrp+ZhIgTWO2lCfxL7SErmtfN+BxEhFgoARn0u6xtzYTj/k3JF2mUncaEnk1EaZnAIUM37gXwQi3MOXitACnVrb5QSACX1ZsYNrPVpnug=
    # AWS prod
    - secure: ER3dLM/AezZM8C8a56B+ySmHdVJM+nDRKAkyFwnUIQo2RUt+T/dAOlT1NnN1FwCAvdRwvpKdbjIfZ/z1Rs8/9EVAGRDXiy/zIYsbQnLIw8+jLvy9wxb9S/4sZF9d3piba5nB3tfDk+Y7s8OxcvCB2sANr6gE3sKe/NGHwGRZqpnL9yezRT1Dnyp9pStORSjUEvKYJKmqncSLwjthA49rIF1EeBLMAwXXaKRZXyeZNd09ZKjJyopWddULG4qmaS2Fl57XhNpkNVZFtK3+Eg6qovcSLITQH2+MISfY0mj/OHzZL+uqooMHhVqGiR13+WsdzXoQ2/XaCa+3V4rDM4m0dBz0M0B5zTcAoUCoK5lGLaD/xjE5Uwg3po/bcdUQ3GSZMy0WledA8kXy9PM445RisJuFwbVA4uXb58gxy2WLvMB4QPuXteJepUX1crRmVf2tR/ut/NQJ8P7O+8mG0pwbDjpqETTew4cyjLnA7CKFIVFMczw/6BamosOYHIO5UnvRq9auHeUkGjVmu4fwQe7TK1uL+twZCESA/UNzsXwYUrhbTbicJTB56RicxKY1RwGCYC3HPzMjUFb1A/NYSy78lSL8T3rxtldFLclZ5Mn/SlVPCG4hQx0kpA9kxoCwSAvl8Py1LjNKv/JRAOFTQ/EX9UO/r8l1FmqYvjxCAR+ZNBg=
      # Google maps
    - secure: Pgu9LQE6KUI/ism6vGSPWgL3Xjs4OctRBIQfUFQJE82jZNk2ZA0+VCquoItOEjV0OlTLVhpgusNyLGtPepWidHuWBHQI24IKNMa4W6R22WFjYB+zRhxJWIcCywaE0RH3iH7e5npAJmUmDZjqdK5d+ZrSfAivi7cXwss8qL6CfI7oIUYYJYqy+JrE2lrRO7dTNemcEiSjW4gFR4u9UQTWUxa67Fqd2isBlu9gOFOFdf0KUs9YsacIIhXY9n+jvJ3ZuVtrQUq4+AosUj1jHftVKNL+65vSQxK1kuD9dyO0cOO9w8rFPLg1mkxZBpHNWzDog1MTQzJRUlZmtdpTqZnB/VTgyeva0+C/b1/w+dxmwA3hKAW0kssax89hQzV9mCGFEIVdlvVhMkVm7ql37PihzL2EUJ7xhwExswYC5PkplCOoh+88WGh5wLIfBO52rQyEWCMwBpKKqaZBqorCJ55q/fa3kRJemJasPQ9KcW3HY0xwzcKsFHyz4o16smllJ6om1TeWH/7f5xUrFSdTf60aFJGAV5SnuMSXPuldOepe288IJEh2QGMCYGL2K+4xlVDkCVL7uVwhge4mKIQc+B7CwGWf2myZYWA5sI9OzmqaZU9FAc0mZViSBWoOwrdDqyaIGo2ryNOVA1b4FokBnsXWqRusxKoQ+pT0VPu0IVbOHPQ=
install: npm install
before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"
after_success:
  - echo 'All tests passed; Preparing to deploy'
  - "./provisioning/deploy"
