language: node_js
node_js:
  - 14
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
    # AWS dev
    - secure: LtvGEuu9U/wYh1DYRcZWNiRn1tVAUN/ELspxcBFUVXSoe0golVrlTgiH5TP7MuziBPvhuhANeAGmoV8cLXRhY+pVhFO64BmIn8koQyb2aF73Vz3/fBn67wjtmZlK7JVVqCP5ynnUHKiU1c52fySvsIFLW8saPzV60rRN5lk2JDmP0vuYIn6mDZAvQeotmSqGdOmYxsT238B+HfTutP+6ukccEB2ZOoUZ0Y25T8uUvIJlthyGgE527/L7sjZAxGFp/jF519rx4taH9iekbyDmJIcJ1IsTM1w6DkiXdtg49hIPvsTt0PIwJ5CnOzaKh+96/uaghJ3r8G23QISNJYfOKDBWR2GxgRFbMKiBr5wB9qE3KNIdZo5fyqPTQg55D/Fd81uLHBZDF8ldkEyhUP+zRWo2uOFYW4v9zvjRphO/rG7FCXw1jDP7CeGdubgCesnhkwapoPA9gMezrNOnTls21M0dkfYDFTaRmw6PR9lvsV3zLQ5EBkScUf9aMsToZ7XbWF46Fzu8cjtG/9I9TXCNJqWrHRfu+JZsJMPtppxi80KFXhW8Z5rnc7owR6rD48EZwqYC2YkIxwcGnVI0rPw10zrzr3WWhP4ZgMjFFxL7a5aOe7v2RbPhFtvF3mCFVWVEPxEZweaCB6oBK/UPKis3xhJHkDeLlj4meejMy+W9FU0=
install: npm install
before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"
after_success:
  - echo 'All tests passed; Preparing to deploy'
  - "./provisioning/deploy"
