language: node_js
dist: trusty

node_js:
- 7

services:
- docker

cache:
  directories:
  - node_modules

branches:
  only:
  - qa
  - production

env:
  global:
  - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  - secure: BpCzsw7HGhcWFQupoWp8svlrX4VWHle8eJ8coK0vGRxMINPxPNitatzXeAEmf/Qqp+vyGbEKN0j70LitQg7883UAHQLc3be9V71R1Oc4FjDeYh7vbLA7euxEOTzCoBFc9Gt7z0Yo9cSDoftVyuprjHILCUEYZDs/Itz1I42uKlM1mj3CgbFwP7/541AboNXEjPbHwGiuyiG6XgUzVRx9h/4IUBpqjWxSQdePXaNKiUNl8gkKIp1NZqsUpx9wUrme/55RBPN+VH1mMxn+4V0RBrWKEQhW65wziGt0UMs6d1fCzLlscLkBwvOHOEJnkq9RXax/rG8WUhzjNjupjyqx7Kq82cl7Vz1bzkUXoGy/YrPPFelCtH2/YLJ0ku6WpfbIyqNhjHiql3/GgQJjECesd812FjTfFi0HaADQpcBhm+b6G7QEB04iIpYVdP9hRfleheW0sKfXpTAMhsEEnGmUUZueURDURdgmjSKb0WFo0T+HjTxhhoTZ9NomgmofqEjx08pn3cj3jzGtTetwJdu3tMRpqARTB9DmpqpdWyOyhXTUW22XAKQwCKhtSu8cvcLjNgG3feARfNeZNMmhTKIagul88llthd7WTztqtjLFpxnNK1MEMwKutNCY2vlN0q7uvSgmUQtDnIMISWPsDrTMNMfctniKGgeLqvkqqtK0qlY=

install: npm install

before_script:
  - cp .travis/.env .
  - "./provisioning/set-env"

script: npm test

before_deploy: echo 'All tests passed; Preparing to deploy'

deploy:
  provider: script
  script: provisioning/deploy
  on:
    all_branches: true
