language: node_js
dist: trusty

node_js:
- 14

services:
- docker

branches:
  only:
  - qa
  - production

env:
  global:
  - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  - secure: qTAJ6ojzZpIVnywqBMOR9suy2aQa+XWIi/tmy1dhyI0uH07dTpFLMXPkoiyj6OykaPJU8blUFUXRHRtdnfspWGKaXAGdBOLvf1gdiRyRvW3MXPzQ03BhHrSM4D56ADq70FBtkscHuXYEu+edXQZL5Z2/LdrpXKIjzDjwx0xpr11z1B9peW0Ild1FS7NaD3gOCxDrOxREwGINbhhvquSycSiGWO87Huo2pUi45hCoiBPQJyHMxN6Xlwo+OTx36/EkQHTQ9Mdgwai81zZNFmc1DIhMBa/w99DC9jV3X//NyhQUWfxRlYRQ2FvuR1Dky4VfU5qwL+f8Gs2zgPRka5A/BQYPTtaX5IRUcAoAIrK2Z1bPjxJ7g3iqg07hM6KWXAVYJC0/v2zfFYcUfeKcEzyTIX6xJUw43ApOal5G9tFHjO/pvHFYHIlkG9zvqCnoUAvzYcE4hRyF9VeYygp7wlrT3D0yrvtGSyzigX7eq3LOoOCFAHFDtkMvxZUcmxwY7wqC1vJiJzW3OmNe139rnx9C5hEFdCWjduMieqI6f3QTI65Q0lhLk55W3zUrakS1LFq/vHEJ0yRN7f0kt+O15OZG/RnjrAC+O1eE0Cos9WFTlrhNbYTCgT58Vx/ept375TnnnEfBe07nF5VTl1ulKHZDmtIUuYSK/HOssv5m3mcZkhM=

install: npm install

before_script:
  - cp .travis/.env .
  - ./provisioning/set-env

after_success:
  - echo 'All tests passed; Preparing to deploy'
  - ./provisioning/deploy