language: node_js
dist: trusty

node_js:
  - 7

services:
  - docker

cache:
  directories:
    - node_modules

branches:
  only:
    - qa
    - production

env:
  global:
  - NODE_ENV=14
  - REMOTE_IMAGE_URL_NYPL_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  - REMOTE_IMAGE_URL_NYPL=463786892988.dkr.ecr.us-east-1.amazonaws.com/nypldxpsearch
  # All secure variables for scripts.
  - secure: nsKDFOzIqFgJO7slWE06UD6s+NkgcgG1tQ7hR/AvMnVF9fUGFQSAIXhsURZIpMWFCmtkNgPR//ySTWHvDsyMJzPkNFUZlwO9vniDxKZrlrHi534e9anEYfc/mnuxdnp4of2ox7SV3P5UjCwjfkh35pgKMzINFrEiEnv1a76f9CUWI4qcvSiCDpcWIWd9rVuWYaOny9SLZXwNqnKACGieQqAqdNRTcpd0RSvEnT+xjkW5VMlUxnnetvjgtzfxeG4nd/xcIuCrl/5RdejvV7j3WQM6DgSPAvQgCHqdyzHqFqKBe6eilnha9mZdzSLjX/MHL4jDsiCBeK2X1pbt2cff2yas6f7AbtUwoJsBFyuUhZA9S45mZR2JUPrRWTgV8ryweEeryEBZZab6mTPLIsAGmfAhzfKSYYlBr2kIbqhAizaJG3WQpKMuv9T83b+h4YNeW6AhS6zd1F+IKdzQyugQNs2YafX15XK2b+pwB1WWQkXuUj35EUOUJzhS3x99wrpO+C1bTKEu0o4DrP4km56khRsexRbC34BtFJKFil+8TD3VKsD4yoSQCFgi/fWrvkUkNufuq0uWzu5WqIOU87sOWA7eAh4zdKcdSgD1A7OmJ1IbeiCrJ62+l+xUppawc2mwai/l/5U3P3rfj2DeStFukDFKnZKJ3G7gVVgRk0mGBqU=

install: npm install

before_script:
  - cp .travis/.env .
  - ./provisioning/set-env

script: npm test

before_deploy: echo 'All tests passed; Preparing to deploy'

deploy:
  provider: script
  script: provisioning/deploy
  on:
    all_branches: true