query LocationsQuery(
  $searchGeoLat: Float,
  $searchGeoLng: Float,
  $openNow: Boolean,
  $termIds: [TermsFilter],
  $limit: Int,
  $pageNumber: Int,
  $offset: Int) {
  allLocations(
    limit: $limit,
    pageNumber: $pageNumber,
    offset: $offset,
    filter: {
      openNow: $openNow,
      termIds: $termIds
    },
    sortByDistance: {
      originLat: $searchGeoLat,
      originLng: $searchGeoLng
    }
  ) {
    locations {
      id
      name
      contentType
      slug
      url
      status
      address_line1
      address_line2
      locality
      administrative_area
      postal_code
      phone
      wheelchairAccess
      accessibilityNote
      geoLocation {
        lat
        lng
      }
      todayHours {
        start
        end
      }
      open
    }
    pageInfo {
      totalItems
    }
  }
}
