query SearchDocumentQuery(
  $q: String,
  $limit: Int,
  $pageNumber: Int,
  $offset: Int
) {
  allSearchDocuments(
    limit: $limit,
    pageNumber: $pageNumber,
    offset: $offset,
    filter: {
      q: $q
    }
  ) {
    items {
      id
      name
      description
      ... on OnlineResourceDocument {
        accessibilityLink
        termsConditionsLink
        privacyPolicyLink
        notes
        updateFrequency
        printEquivalent
        format
        language
        outputType
      }
    }
    pageInfo {
      totalItems,
      limit,
      pageNumber,
      pageCount,
      timestamp
    }
  }
}