query SearchResultsQuery(
  $q: String,
  $limit: Int,
  $pageNumber: Int,
  $offset: Int
) {
  allOnlineResourcesSearch(
    limit: $limit,
    pageNumber: $pageNumber,
    offset: $offset,
    filter: {
      q: $q
    }
  ) {
    items {
      id
      name
      description
    }
    pageInfo {
      totalItems,
      limit,
      pageNumber,
      pageCount,
      timestamp
    }
  }
}