services:
  nginx:
    image: tugboatqa/nginx:1
    default: true
    commands:
      init:
        # Adding the NodeSource APT repository AND the PGP key for verifying packages
        - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        - apt-get install -y nodejs
        - node --version
        - npm --version
      build: 
        - pwd
        - ls -la
        - npm install
        - npm run build
        - npm start