services:
  node:
    image: tugboatqa/httpd
    expose: 3000
    commands:
      build:
        - apt-get update
        - apt-get install nodejs
        - apt-get install npm
        - npm install
        - npm run build
        - npm start &
#        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
