services:
  node:
    image: tugboatqa/node:14
    expose: 3000
    commands:
      build:
        # We're already in the correct directory, so we can run npm install.
        - npm install
        # Run the NextJS production build.
        - npm run build
        # Run the tests
        #- npm test
      start:
        - npm start &