query LocationByInternalSlugQuery(
  $contentType: String
  $limit: Int
  $pageNumber: Int
  $filter: LocationFilter
  $sort: Sort
) {
  allLocations(
    contentType: $contentType
    limit: $limit
    pageNumber: $pageNumber
    filter: $filter
    sort: $sort
  ) {
    items {
      id
      name
      internalSlug
      email
      url
    }
    pageInfo {
      limit
      totalItems
    }
  }
}
