query OnlineResourceByIdQuery($id: String) {
  searchDocument(id: $id) {
    ... on OnlineResourceDocument {
      id
      slug
      name
      description
      accessibilityLink
      termsConditionsLink
      privacyPolicyLink
      subjects {
        id
        name
      }
      accessLocations {
        id
        name
      }
      notes
      updateFrequency
      printEquivalent
      format
      language
      outputType
    }
  }
}