query TaxonomyTermsQuery($vocabulary: String) {
  allTermsByVocab(vocabulary: $vocabulary) {
    id
    tid
    name
    description
    url
    image {
      id
      alt
      uri
      transformations {
        id
        label
        uri
      }
    }
  }
}
