query ChannelCardsQuery($type: String) {
  allChannels(type: $type) {
    id
    tid
    name
    description
    image {
      id
      alt
      uri
      transformations {
        id
        label
        uri
      }
    }
    url
  }
}
