query ChannelCardsQuery($type: String) {
  allChannels(
    type: $type
  ) {
    id
    tid
    name
    description
    imageUrl
    image {
      id
      alt
      items {
        label
        uri
      }
    }
    url
  }
}