query ResourceTopicsQuery(
  $featured: Boolean, 
  $mostPopular: Boolean
) {
  allResourceTopics(
    filter: {
      featured: $featured,
      mostPopular: $mostPopular
    }
  ) {
    id
    name
    description
    imageUrl
  }
}